# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=120)),
                ('field2', models.CharField(max_length=120)),
            ],
        ),
    ]
