# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubcater',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
